name:    restyled
version: "0.0.0"
dependencies:
- base

- aeson
- bytestring
- case-insensitive
- classy-prelude
- classy-prelude-conduit
- classy-prelude-yesod
- conduit
- containers
- data-default
- directory
- envparse
- fast-logger
- file-embed
- hjsmin
- HTTP
- http-client
- http-client-tls
- http-conduit
- http-types
- jwt
- load-env
- monad-control
- monad-logger
- network-uri
- persistent
- persistent-postgresql
- persistent-template
- process
- safe
- shakespeare
- template-haskell
- temporary
- text
- time
- unordered-containers
- vector
- wai
- wai-extra
- wai-logger
- warp
- yesod
- yesod-core
- yesod-form
- yesod-static

library:
  source-dirs: src
  when:
  - condition: flag(dev)
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

executables:
  restyled:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - restyled

  restyler:
    main: main.hs
    source-dirs: restyler
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - restyled
    - filepath
    - optparse-applicative

tests:
  test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - restyled
    - hspec
    - hspec-expectations-lifted
    - yesod-test

flags:
  library-only:
    description: Unused, but yesod-devel passes it.
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
