# yamllint disable rule:line-length
version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        environment:
          GIT_AUTHOR_EMAIL: ci@restyled.io
          GIT_AUTHOR_NAME: Restyled.io CI
          GIT_COMMITTER_EMAIL: ci@restyled.io
          GIT_COMMITTER_NAME: Restyled.io CI
          STACK_ARGUMENTS: --no-terminal
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
      - image: redis:4.0.2-alpine
    steps:
      - checkout
      - run:
          name: Digest
          command: git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - v1-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
            - v1-{{ .Branch }}-{{ checksum "stack.yaml" }}-
            - v1-{{ .Branch }}
            - v1-
      - run:
          name: Dependencies
          command: |
            make setup setup.lint
            curl "$HLINT_YAML_SRC" > .hlint.yaml
          environment:
            HLINT_YAML_SRC: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
      - run:
          name: Build
          command: make build
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Migrate
          command: db/migrate test upgrade
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint
      - run:
          name: Tag Master Build
          command: |
            if [ "$CIRCLE_BRANCH" = master ]; then
              # Two tags, each one becomes a separate Docker image
              git tag -a -m "web-b$CIRCLE_BUILD_NUM" "web-b$CIRCLE_BUILD_NUM"
              git tag -a -m "backend-b$CIRCLE_BUILD_NUM" "backend-b$CIRCLE_BUILD_NUM"
              git push --tags
            fi

  # Triggered manually via API to deploy image built in Quay
  deploy:
    docker:
      - image: quay.io/restyled-io/ops
    steps:
      - setup_remote_docker
      - run:
          name: Deploy
          command: |
            registry=registry.heroku.com

            case "$DEPLOY_TAG" in
              web-b*) image=$registry/restyled-io/web ;;
              backend-b*) image=$registry/restyled-io/backend ;;
              *)
                echo "Invalid DEPLOY_TAG: $DEPLOY_TAG" >&2
                exit 1
                ;;
            esac

            docker login \
              --email "$HEROKU_EMAIL" \
              --password "$HEROKU_API_KEY" \
              "$registry"

            docker pull "$DEPLOY_IMAGE:$DEPLOY_TAG"
            docker tag "$DEPLOY_IMAGE:$DEPLOY_TAG" "$image"
            docker push "$image"
            notify "restyled-io" "Deploy of $image ($DEPLOY_TAG) successful"
