version: 2.0

jobs:
  build_and_test:
    docker:
      - image: fpco/stack-build:lts
      - image: circleci/postgres:9.4.12-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
    steps:
      - checkout
      - restore_cache:
          keys: stack
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - stack-{{ .Branch }}
            - stack
      - run:
          name: Dependencies
          command: |
            set -e
            stack setup
            stack install hlint
            stack install weeder
            stack build --dependencies-only --test --no-run-tests
      - run:
          name: Build
          command: |
            stack build --pedantic --test --no-run-tests
      - run:
          name: Lint
          command: |
            set -e
            hlint .
            weeder .
      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: stack test

  deploy:
    docker:
      - image: docker:17.07.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.07.0-ce
      - run:
          name: Dependencies
          command: apk add --update make
      - restore_cache:
          keys:
            - docker-{{ .Branch }}
            - docker-master
            - docker
          paths:
            - /caches/restyled.io.tar
      - run:
          name: Load image cache
          command: |
            docker load -i /caches/restyled.io.tar || true
      - run:
          name: Build image
          command: make restyled.io
      - run:
          name: Save image cache
          command: |
            mkdir -p /caches
            docker save -o /caches/restyled.io.tar restyled.io/restyled.io
      - save_cache:
          key: docker-{{ .Branch }}
          paths:
            - /caches/restyled.io.tar
      - deploy:
          name: Staging
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login \
                --username="$HEROKU_EMAIL" \
                --password="$HEROKU_API_KEY" \
                registry.heroku.com
              make release
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
