# yamllint disable rule:line-length
version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts-14.6
        environment:
          STACK_ARGUMENTS: --no-terminal
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
      - image: redis:4.0.2-alpine
    steps:
      - checkout
      - run:
          name: Digest
          command: git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            - v5-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
            - v5-{{ .Branch }}-{{ checksum "stack.yaml" }}-
            - v5-{{ .Branch }}
            - v5-
      - run:
          name: Dependencies
          command: make setup setup.lint
      - run:
          name: Build
          command: make build
      - save_cache:
          key: v5-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Migrate
          command: db/migrate test upgrade
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint

  image:
    docker:
      - image: restyled/ops:v6
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Build
          command: |
            sha=${CIRCLE_SHA1:0:10}
            release_image=restyled/restyled.io:$sha

            docker login \
              -u "$DOCKERHUB_USERNAME" \
              -p "$DOCKERHUB_PASSWORD"

            docker-build-remote-cache "$release_image" \
              --build-arg "REVISION=$CIRCLE_SHA1"

  release-frontend:
    docker:
      - image: restyled/ops:v6
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Release
          command: |
            sha=${CIRCLE_SHA1:0:10}
            release_image=restyled/restyled.io:$sha

            cat >Dockerfile.web <<EOM
            FROM $release_image
            CMD ["/app/restyled.io", "web"]
            EOM

            heroku container:login
            heroku container:push --recursive --app restyled-io
            heroku container:release web --app restyled-io
            notify "restyled-io" "Frontend deployed at $sha"

  release-backend:
    docker:
      - image: restyled/ops:v6
    steps:
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: Release
          command: |
            sha=${CIRCLE_SHA1:0:10}
            release_image=restyled/restyled.io:$sha

            ecs deploy restyled-prod webhooks \
              --region us-east-1 \
              --image restyled-backend "$release_image"

            for cmd in health sync-marketplace; do
              ecs cron restyled-prod "$cmd" \
                --region us-east-1 \
                --task restyled-prod-backend \
                --command restyled-backend "/app/restyled.io,$cmd"
            done

            notify "restyled-io" "Backend deployed at $sha"

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - image
      - release-backend:
          requires:
            - build
            - image
          filters:
            branches:
              only:
                - master
      - release-frontend:
          requires:
            - build
            - image
          filters:
            branches:
              only:
                - master
