version: 2.0

jobs:
  build:
    docker:
      - image: fpco/stack-build:lts
        environment:
          STACK_ARGUMENTS: --no-terminal
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
      - image: redis:4.0.2-alpine
    steps:
      - checkout
      - run:
          name: Digest
          command: git ls-files | xargs md5sum > digest
      - restore_cache:
          keys:
            # yamllint disable-line rule:line-length
            - v1-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
            - v1-{{ .Branch }}-{{ checksum "stack.yaml" }}-
            - v1-{{ .Branch }}
            - v1-
      - run:
          name: Dependencies
          command: |
            make setup setup.lint
            curl "$HLINT_YAML_SRC" > .hlint.yaml
          environment:
            # yamllint disable-line rule:line-length
            HLINT_YAML_SRC: https://raw.githubusercontent.com/pbrisbin/dotfiles/master/hlint.yaml
      - run:
          name: Build
          command: make build
      - save_cache:
          # yamllint disable-line rule:line-length
          key: v1-{{ .Branch }}-{{ checksum "stack.yaml" }}-{{ checksum "digest" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Migrate
          command: db/migrate test upgrade
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make lint
      - run:
          name: Release
          command: |
            if [ "$CIRCLE_BRANCH" = master ]; then
              make release VERSION=$CIRCLE_BUILD_NUM
            fi
