---
version: 2.0

jobs:
  tests:
    docker:
      - image: fpco/stack-build:lts
      - image: circleci/postgres:9.6.5-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: restyled_test
      - image: redis:4.0.2-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
            - stack-{{ .Branch }}
            - stack-
      - run:
          name: Dependencies
          command: make setup
      - run:
          name: Build
          command: make build
      - run:
          name: Lint
          command: make lint
      - save_cache:
          key: stack-{{ .Branch }}-{{ checksum "stack.yaml" }}
          paths:
            - ~/.stack
            - ./.stack-work
      - run:
          name: Test
          command: make test

  image:
    docker:
      - image: docker:17.07.0-ce
    steps:
      - checkout
      - setup_remote_docker:
          reusable: true
          version: 17.07.0-ce
      - run:
          name: Dependencies
          command: apk add --update make
      - run:
          name: Build image
          command: |
            make image.build
      - run:
          name: Push image
          command: |
            make image.release \
              DOCKER_USERNAME=$DOCKERHUB_USERNAME \
              DOCKER_PASSWORD=$DOCKERHUB_PASSWORD \
              RELEASE_IMAGE=restyled/restyled.io:b$CIRCLE_BUILD_NUM

  deploy:
    docker:
      - image: restyled/ops
    steps:
      - deploy:
          name: Deploy
          command: |
            if [[ "$CIRCLE_BRANCH" == master ]]; then
              restyled-ops update \
                --message "[PROD] restyled.io => b$CIRCLE_BUILD_NUM" \
                "AppsImageTag=b$CIRCLE_BUILD_NUM"
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - tests
      - image:
          context: org-global
      - deploy:
          context: org-global
          requires:
            - tests
            - image
